- job-template:
    name: myvendor-devstack-tempest-volume-api

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps
    
    triggers:
      - gerrit:
        trigger-on-comment-added-event: true
        trigger-on-patchset-uploaded-event: true
        trigger-on-patchset-restored-event: true
        gerrit-build-successful-verified-value: 1
        gerrit-build-failed-verified-value: -1
        successful-message: Looks good according to MyVendor!
        failure-message: Does not seem to work for MyVendor!
        projects:
          - project-compare-type: 'PLAIN'
            project-pattern: 'openstack/cinder'
            branch-compare-type: 'ANT'
            branch-pattern: '**'
        skip-vote:
          successful: false
          failed: false
          unstable: true
          notbuilt: true
        silent: false
        escape-quotes: true
        no-name-and-email: true

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_VOLUME_API=1
          export RE_EXEC=true
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log
