- job-template:
    name: 'dsvm-tempest-xen'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185  # Timeout in *minutes*
          fail: true  # A job run that exceeds the timeout will cause a failure
      - timestamps

    builders:
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe

          function pre_test_hook {{
              echo "Install thirdparty libraries"

              # Install libvirt here to ensure it is
              # not replaced devstack
              sudo dpkg -i /opt/nodepool-scripts/*.deb
              sudo apt-get install -y -f --fix-missing
          }}
          function _exit_trap {{
              code=$?
              echo "Copying custom logs"

              # Xen logs
              if [ -d /var/log/xen ]; then
                  sudo cp -r /var/log/xen /opt/stack/logs/
                  sudo chmod a+wrx -R /opt/stack/logs/xen
              fi

              exit $code
          }}

          export -f pre_test_hook
          trap _exit_trap EXIT

          if [ -z $ZUUL_PROJECT ]; then
              export ZUUL_PROJECT=openstack-dev/sandbox
          fi
          if [ -z $ZUUL_BRANCH ]; then
              export ZUUL_BRANCH=master
          fi
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_VIRT_DRIVER=libvirt
          export DEVSTACK_GATE_LIBVIRT_TYPE=xen
          export DEVSTACK_GATE_TIMEOUT=180
          #export DEVSTACK_GATE_TEMPEST_REGEX='^(?!.*test_volume_boot_pattern).*'
          export DEVSTACK_GATE_TEMPEST_REGEX='(?!.*\[.*\bslow\b.*\]|.*test_volume_boot_pattern)(^tempest\.(api|scenario|thirdparty))'
          export RE_EXEC=true
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs  # In macros.yaml from os-ext-testing

    publishers:
      - osci-swift-upload-logs-with-console:
          upload_source: 'logs'
